fasta_dir: /homes/heng.ma/Research/BVBRC/seqs
hf_dir: /homes/heng.ma/Research/md_pkgs/sequence_study/inference_scaling/cache
num_parallel_tasks: 3

compute_settings:
  name: workstation
  available_accelerators: [5,6,7] # [1,2,3,5,6,7]
